#!/usr/bin/env bash
#====================HEADER==========================================|
#AUTOR
# Jefferson 'Slackjeff' Rocha <root@slackjeff.com.br>
#
#LICENCE
# MIT
#
#PROGRAM
# holesurf - Syncronize Holes on underhole network.
#
#LICENSE
# MIT
#
#CHANGELOG
# View on changelog.txt
#====================================================================|


##############################################
# VARS
##############################################
export PRG='holesurf'               # Name Program
export USERDIR="${HOME}/.underhole" # Directory of ALL holes
export HOLELIST="${USERDIR}/holelist.txt"
export BROWSER='lynx'               # Default Browser
export RSYNC_PASSWORD=''            # Inicialize variable

#COLORS
red='\033[31;1m'
yellow='\033[33;1m'
blue='\033[34;1m'
end='\033[m'
bg_dir='\033[37;44;1m'
bg_file='\033[37;41;1m'

##############################################
# FUNC
##############################################

# Read a CSV hole-list
_READ()
{
    local c1 c2 c3
    local IFS

    while IFS='&' read -r c1 c2 c4 c5 c6; do
        [[ "$c1" =~ ^# ]] && continue
        echo -e "HOLE:\t${c1}\nIP:\t${c2}\nPORT:\t${c5}\nCOM:\t${c6}\n--------------------------------------------\n"
    done <"$HOLELIST"
    return 0
}

# Password + Salt For secure BD.
_SECURE_PASS()
{
    local salt_size='5' # Tamanho que terá o salt
    local delimiter=':'
    local PASSWORD="$1"

    # Nulo cai fora
    [[ -z "$PASSWORD" ]] && { echo "The input parameter is null."; return 1 ;}
    # Gerando sal randômico
    SALT="$(head /dev/urandom | tr -dc "0-9a-zA-Z" | head -c "$salt_size"; echo)"
    # Printa pra noix
    printf "${SALT}${delimiter}"
    printf "${PASSWORD}${SALT}" | sha256sum | cut -d ' ' -f 1
}

##############################################
# TEST
##############################################
[[ "$UID" = '0' ]] && { echo "Root? Is not secure. ABORT"; exit 1 ;} # Root?
[[ ! -d "$USERDIR" ]] && mkdir -v "$USERDIR" # create a underhole directory
if [[ ! -e "$HOLELIST" ]]; then # Exist hole-list?
    echo 'dadhole&192.168.0.2&thedadhole&12000&The 1s Hole Wiki.' >> "$HOLELIST"
fi

##############################################
# MAIN
##############################################

case $1 in
    sync) # Sync hole-list
          shift # down
          OLDIFS="$IFS" # Save IFS.
          inc='0' # Increment var
          # Print
          while IFS='&' read -r column1 column2 column3 column4; do
              [[ "$column1" =~ ^# ]] && continue
              echo -e "${red}[ $inc ]${end} $column1-$column2"
              options[i++]="$column1&$column2&$column3&$column4" # Capture all line
              inc=$(($inc + 1)) # Inc for Menu
          done < "$HOLELIST"
          read -p $'\n\033[37;44;1mServer to Sync:\033[m ' select_server
          if ! [[ "$select_server" =~ ^[0-9]+$ ]]; then
              echo "$select_server Invalid Option."
              exit 1
          fi
          # Capture Fields and Sync
          HOLE="$(cut -d '&' -f 1 <<< ${options[$select_server]})"
          HOST="$(cut -d '&' -f 2 <<< ${options[$select_server]})"
          PASS="$(cut -d '&' -f 3 <<< ${options[$select_server]})"
          PORT="$(cut -d '&' -f 4 <<< ${options[$select_server]})"
          # Convert Hash + Salt
          
          # Password arg Rsync
          RSYNC_PASSWORD="$PASS"
          echo -e "${blue}Syncing${end} ${USERNAME} ${blue}ON${end} ${HOST} ..."
          if rsync -avzh rsync://${HOLE}@${HOST}:${PORT}/hole/ "${USERDIR}/${HOLE}"; then
              echo -e "${yellow}========Sync OK${end}"
              echo -e "${blue}========Available in:${end} ${USERDIR}/${HOLE}"
              $BROWSER "${USERDIR}/${HOLE}"
          else
              echo -e "${red}========SYNC ERROR. ${HOLE}${HOST}${end}"
          fi
    ;;

    show)
          shift # Down.
          [[ -e "$HOLELIST" ]] && _READ
    ;;
esac

